name: dotnet package

on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        options:
          - framework: net6.0
          - framework: net5.0
          - framework: netcoreapp3.1
    steps:
      - uses: actions/checkout@v2
      - name: DotNetBuild
        shell: pwsh
        run: ./ci-build.ps1 "${{matrix.options.framework}}"
      - name: Test
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Codecov
        uses: codecov/codecov-action@v1